# Generated by Django 5.2.11 on 2026-03-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='proposed_action',
        ),
    ]
