# Generated by Django 5.2.11 on 2026-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0003_request_reviewed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
