# Generated by Django 5.2.11 on 2026-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "approvals",
            "0005_remove_request_category_remove_request_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
